#!/bin/bash
#############################################################
# Name:        Supportconfig Plugin for SUSE Enterprise Storage
# Description: Gathers important troubleshooting information
#              about SUSE Enterprise Storage
# License:     GPLv2
# Author:      Tim Serong <tserong@suse.com>
# Modified:    2015-02-13
#############################################################

SVER=1.0.0
RCFILE="/usr/lib/supportconfig/resources/scplugin.rc"
LOG_LINES=5000  # 0 means include the entire file

[ -s $RCFILE ] && . $RCFILE || { echo "ERROR: Initializing resource file: $RCFILE"; exit 1; }

# Helper functions liberated from Matt Barringer's supportutils-plugin-susecloud
validate_rpm_if_installed() {
    thisrpm="$1"
    echo "#==[ Validating RPM ]=================================#"
    if rpm -q "$thisrpm" >/dev/null 2>&1; then
        echo "# rpm -V $thisrpm"

        if rpm -V "$thisrpm"; then
            echo "Status: Passed"
        else
            echo "Status: WARNING"
        fi
    else
        echo "package $thisrpm is not installed"
        echo "Status: Skipped"
    fi
    echo
}

#############################################################
section_header "Supportconfig Plugin for SUSE Enterprise Storage, v${SVER}"
rpm_list=/usr/lib/supportconfig/resources/ses-rpm-list
for thisrpm in $(cat "$rpm_list"); do
    validate_rpm_if_installed "$thisrpm"
done

#############################################################
section_header "Ceph cluster status"

mkdir $LOG/ceph

if [ -x /usr/bin/ceph ]; then
    # timeout status commands after 5 seconds
    CT=5
    plugin_command "ceph --connect-timeout=$CT -s" > $LOG/ceph/ceph-status 2>&1
    plugin_command "ceph --connect-timeout=$CT mon dump" > $LOG/ceph/ceph-mon-dump 2>&1
    plugin_command "ceph --connect-timeout=$CT osd tree" > $LOG/ceph/ceph-osd-tree 2>&1
    plugin_command "ceph --connect-timeout=$CT osd df tree" > $LOG/ceph/ceph-osd-df-tree 2>&1
    # `ceph report` does actually include the above information, but
    # in JSON format.  Since adding `ceph report`, the above commands
    # remain, because their output is easier to read in a hurry ;)
    plugin_command "ceph --connect-timeout=$CT report" > $LOG/ceph/ceph-report 2>&1
    plugin_command "timeout $CT rados df" > $LOG/ceph/rados-df 2>&1
    plugin_command "timeout $CT rbd ls" > $LOG/ceph/rbd-ls 2>&1

    plugin_message "Cluster status dumped to ceph subdirectory"
else
    plugin_message "/usr/bin/ceph not found"
fi

if [ -x /usr/sbin/ceph-disk ]; then
    plugin_command "ceph-disk list" > $LOG/ceph/ceph-disk-list 2>&1
else
    plugin_message "/usr/sbin/ceph-disk not found"
fi

#############################################################
section_header "Ceph config"

if [ -d /etc/ceph ]; then
    if files=$(find /etc/ceph -type f | egrep -v '.keyring$'); then
        if [ -n "$files" ]; then
            mkdir $LOG/ceph/conf
            for f in $files ; do
                pconf_files $f > $LOG/ceph/conf/$(basename $f)
            done
            plugin_message "Ceph config copied to ceph/conf subdirectory"
        fi
    fi
fi

#############################################################
section_header "Ceph log files"

if [ -d /var/log/ceph ]; then
    mkdir -p $LOG/ceph/log/ceph
    cp /var/log/ceph/*.log $LOG/ceph/log/ceph/
    plugin_message "Ceph logs copied to ceph/log subdirectory"
fi
# Depending on how radosgw is configured, its log files may
# be in /var/log/ceph/ (and thus captured above), or may be in
# /var/log/radosgw (which is what the ceph barclamp configures
# for crowbar deploys
if [ -d /var/log/radosgw ]; then
    mkdir -p $LOG/ceph/log/radosgw
    cp /var/log/radosgw/*.log $LOG/ceph/log/radosgw/
fi
# /var/log/ceph-radosgw/ was also used at some point in the past
if [ -d /var/log/ceph-radosgw ]; then
    mkdir -p $LOG/ceph/log/ceph-radosgw
    cp /var/log/ceph-radosgw/*.log $LOG/ceph/log/ceph-radosgw/
fi

#############################################################
section_header "Calamari log files"

if [ -d /var/log/calamari ]; then
    mkdir -p $LOG/ceph/log/calamari
    cp /var/log/calamari/*.log $LOG/ceph/log/calamari/
    plugin_message "Calamari logs copied to ceph/log subdirectory"
fi

#############################################################
section_header "openATTIC log files"

if [ -d /var/log/openattic ]; then
    mkdir -p $LOG/ceph/log/openattic
    cp /var/log/openattic/*.log $LOG/ceph/log/openattic/
    plugin_message "openATTIC logs copied to ceph/log subdirectory"
fi

#############################################################
section_header "Salt config"

if [ -d /etc/salt ]; then
    if files=$(find /etc/salt -type f | egrep -v '.pem$'); then
        if [ -n "$files" ]; then
            pconf_files $files
        fi
    fi
fi

#############################################################
section_header "Salt log files"

plog_files $LOG_LINES /var/log/salt/{master,minion}

#############################################################
section_header "NFS-Ganesha config"

if [ -e /etc/ganesha/ganesha.conf ]; then
    mkdir -p $LOG/ceph/conf/ganesha
    cp /etc/ganesha/ganesha.conf $LOG/ceph/conf/ganesha/
    plugin_message "NFS-Ganesha config copied to ceph/ganesha/ subdirectory"
fi

#############################################################
section_header "NFS-Ganesha log files"

if [ -e /var/log/ganesha.log ]; then
    mkdir -p $LOG/ceph/log/ganesha
    cp /var/log/ganesha.log $LOG/ceph/log/ganesha/
    plugin_message "NFS-Ganesha logs copied to ceph/log subdirectory"
fi
